name: reservastion
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # firebase_core: ^2.25.5
  # firebase_core: ^2.9.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  # firebase_storage: ^11.0.14 
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.17.5
  flutter_admin_scaffold: ^1.2.0
  image_picker: ^1.1.1
  gallery_picker: ^0.5.1
  permission_handler: ^11.3.0
  path: ^1.8.0
  intl: ^0.19.0
  midtrans_sdk: ^0.4.0
  http: ^1.2.1
  fluttertoast: ^8.2.5
  uuid: ^4.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  table_calendar: ^3.1.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mua.png
    - .env
